#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 140
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define PRODUCTION_ID_COUNT 19

enum {
  sym_identifier = 1,
  anon_sym_type = 2,
  anon_sym_COLON = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_fun = 6,
  anon_sym_DASH_GT = 7,
  anon_sym_LBRACK = 8,
  anon_sym_COMMA = 9,
  anon_sym_RBRACK = 10,
  anon_sym_PLUS = 11,
  anon_sym_true = 12,
  anon_sym_false = 13,
  sym_integer = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_string_token1 = 16,
  sym_escape_sequence = 17,
  sym__newline = 18,
  sym__indent = 19,
  sym__dedent = 20,
  sym_source_file = 21,
  sym__definition = 22,
  sym_variant_definition = 23,
  sym_variant_type_value = 24,
  sym_variant_type_value_args = 25,
  sym_record_definition = 26,
  sym_record_type_field = 27,
  sym_tuple_definition = 28,
  sym_function_definition = 29,
  sym_type_param = 30,
  sym_type_param_clause = 31,
  sym_type_list = 32,
  sym_type_arguments = 33,
  sym__type = 34,
  sym_function_type = 35,
  sym_tuple_type = 36,
  sym__simple_type = 37,
  sym_generic_type = 38,
  sym_param = 39,
  sym_parameter_list = 40,
  sym_infix_expression = 41,
  sym_primary_expression = 42,
  sym_literal = 43,
  sym_boolean = 44,
  sym_string = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_variant_definition_repeat1 = 47,
  aux_sym_record_definition_repeat1 = 48,
  aux_sym_type_param_clause_repeat1 = 49,
  aux_sym_type_list_repeat1 = 50,
  aux_sym_parameter_list_repeat1 = 51,
  aux_sym_string_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_type] = "type",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_fun] = "fun",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PLUS] = "+",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_integer] = "integer",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_variant_definition] = "variant_definition",
  [sym_variant_type_value] = "variant_type_value",
  [sym_variant_type_value_args] = "variant_type_value_args",
  [sym_record_definition] = "record_definition",
  [sym_record_type_field] = "record_type_field",
  [sym_tuple_definition] = "tuple_definition",
  [sym_function_definition] = "function_definition",
  [sym_type_param] = "type_param",
  [sym_type_param_clause] = "type_param_clause",
  [sym_type_list] = "type_list",
  [sym_type_arguments] = "type_arguments",
  [sym__type] = "_type",
  [sym_function_type] = "function_type",
  [sym_tuple_type] = "tuple_type",
  [sym__simple_type] = "_simple_type",
  [sym_generic_type] = "generic_type",
  [sym_param] = "param",
  [sym_parameter_list] = "parameter_list",
  [sym_infix_expression] = "infix_expression",
  [sym_primary_expression] = "primary_expression",
  [sym_literal] = "literal",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_variant_definition_repeat1] = "variant_definition_repeat1",
  [aux_sym_record_definition_repeat1] = "record_definition_repeat1",
  [aux_sym_type_param_clause_repeat1] = "type_param_clause_repeat1",
  [aux_sym_type_list_repeat1] = "type_list_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_fun] = anon_sym_fun,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_integer] = sym_integer,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_variant_definition] = sym_variant_definition,
  [sym_variant_type_value] = sym_variant_type_value,
  [sym_variant_type_value_args] = sym_variant_type_value_args,
  [sym_record_definition] = sym_record_definition,
  [sym_record_type_field] = sym_record_type_field,
  [sym_tuple_definition] = sym_tuple_definition,
  [sym_function_definition] = sym_function_definition,
  [sym_type_param] = sym_type_param,
  [sym_type_param_clause] = sym_type_param_clause,
  [sym_type_list] = sym_type_list,
  [sym_type_arguments] = sym_type_arguments,
  [sym__type] = sym__type,
  [sym_function_type] = sym_function_type,
  [sym_tuple_type] = sym_tuple_type,
  [sym__simple_type] = sym__simple_type,
  [sym_generic_type] = sym_generic_type,
  [sym_param] = sym_param,
  [sym_parameter_list] = sym_parameter_list,
  [sym_infix_expression] = sym_infix_expression,
  [sym_primary_expression] = sym_primary_expression,
  [sym_literal] = sym_literal,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_variant_definition_repeat1] = aux_sym_variant_definition_repeat1,
  [aux_sym_record_definition_repeat1] = aux_sym_record_definition_repeat1,
  [aux_sym_type_param_clause_repeat1] = aux_sym_type_param_clause_repeat1,
  [aux_sym_type_list_repeat1] = aux_sym_type_list_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_variant_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_variant_type_value] = {
    .visible = true,
    .named = true,
  },
  [sym_variant_type_value_args] = {
    .visible = true,
    .named = true,
  },
  [sym_record_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type_field] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_param] = {
    .visible = true,
    .named = true,
  },
  [sym_type_param_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_type_list] = {
    .visible = true,
    .named = true,
  },
  [sym_type_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_function_type] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_type] = {
    .visible = false,
    .named = true,
  },
  [sym_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_infix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variant_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_param_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_fields = 1,
  field_name = 2,
  field_parameter_types = 3,
  field_parameters = 4,
  field_return_type = 5,
  field_type = 6,
  field_type_arguments = 7,
  field_type_parameters = 8,
  field_values = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_fields] = "fields",
  [field_name] = "name",
  [field_parameter_types] = "parameter_types",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
  [field_type] = "type",
  [field_type_arguments] = "type_arguments",
  [field_type_parameters] = "type_parameters",
  [field_values] = "values",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 2},
  [9] = {.index = 14, .length = 1},
  [10] = {.index = 15, .length = 2},
  [11] = {.index = 17, .length = 3},
  [12] = {.index = 20, .length = 2},
  [13] = {.index = 22, .length = 3},
  [14] = {.index = 25, .length = 3},
  [15] = {.index = 28, .length = 2},
  [16] = {.index = 30, .length = 3},
  [17] = {.index = 33, .length = 3},
  [18] = {.index = 36, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 0},
  [1] =
    {field_name, 0},
  [2] =
    {field_fields, 3},
    {field_name, 1},
  [4] =
    {field_type, 0},
    {field_type, 1, .inherited = true},
  [6] =
    {field_type, 0},
    {field_type_arguments, 1},
  [8] =
    {field_name, 1},
    {field_values, 4},
  [10] =
    {field_fields, 4},
    {field_name, 1},
  [12] =
    {field_parameter_types, 0},
    {field_return_type, 2},
  [14] =
    {field_type, 1},
  [15] =
    {field_type, 0, .inherited = true},
    {field_type, 1, .inherited = true},
  [17] =
    {field_fields, 4},
    {field_name, 1},
    {field_type_parameters, 2},
  [20] =
    {field_name, 0},
    {field_type, 2},
  [22] =
    {field_name, 1},
    {field_type_parameters, 2},
    {field_values, 5},
  [25] =
    {field_fields, 5},
    {field_name, 1},
    {field_type_parameters, 2},
  [28] =
    {field_name, 1},
    {field_type, 5},
  [30] =
    {field_name, 1},
    {field_parameters, 3},
    {field_type, 6},
  [33] =
    {field_name, 1},
    {field_type, 6},
    {field_type_parameters, 2},
  [36] =
    {field_name, 1},
    {field_parameters, 4},
    {field_type, 7},
    {field_type_parameters, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '+') ADVANCE(19);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '[') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == ']') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(4);
      if (lookahead == 'x') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(28);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '{') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '+') ADVANCE(19);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '[') ADVANCE(16);
      if (lookahead == ']') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 't') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 'y') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_fun);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0, .external_lex_state = 3},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0, .external_lex_state = 2},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0, .external_lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0, .external_lex_state = 3},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 0, .external_lex_state = 3},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 0, .external_lex_state = 2},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0, .external_lex_state = 3},
  [87] = {.lex_state = 0, .external_lex_state = 3},
  [88] = {.lex_state = 0, .external_lex_state = 2},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0, .external_lex_state = 3},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0, .external_lex_state = 3},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0, .external_lex_state = 3},
  [100] = {.lex_state = 0, .external_lex_state = 3},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0, .external_lex_state = 2},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0, .external_lex_state = 3},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0, .external_lex_state = 2},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0, .external_lex_state = 2},
  [119] = {.lex_state = 0, .external_lex_state = 2},
  [120] = {.lex_state = 0, .external_lex_state = 2},
  [121] = {.lex_state = 0, .external_lex_state = 2},
  [122] = {.lex_state = 0, .external_lex_state = 2},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0, .external_lex_state = 2},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0, .external_lex_state = 3},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
};

enum {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [2] = {
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__indent] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(138),
    [sym__definition] = STATE(7),
    [sym_variant_definition] = STATE(7),
    [sym_record_definition] = STATE(7),
    [sym_tuple_definition] = STATE(7),
    [sym_function_definition] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(5),
    [anon_sym_fun] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    STATE(78), 1,
      sym_param,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(106), 2,
      sym_type_list,
      sym_parameter_list,
    STATE(37), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [23] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(108), 1,
      sym_infix_expression,
    STATE(124), 1,
      sym_primary_expression,
    STATE(133), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(127), 2,
      sym_boolean,
      sym_string,
  [50] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(115), 1,
      sym_infix_expression,
    STATE(124), 1,
      sym_primary_expression,
    STATE(133), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(127), 2,
      sym_boolean,
      sym_string,
  [77] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(120), 1,
      sym_infix_expression,
    STATE(124), 1,
      sym_primary_expression,
    STATE(133), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(127), 2,
      sym_boolean,
      sym_string,
  [104] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(124), 1,
      sym_primary_expression,
    STATE(126), 1,
      sym_infix_expression,
    STATE(133), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(127), 2,
      sym_boolean,
      sym_string,
  [131] = 4,
    ACTIONS(5), 1,
      anon_sym_type,
    ACTIONS(7), 1,
      anon_sym_fun,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(8), 6,
      sym__definition,
      sym_variant_definition,
      sym_record_definition,
      sym_tuple_definition,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [149] = 4,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_type,
    ACTIONS(28), 1,
      anon_sym_fun,
    STATE(8), 6,
      sym__definition,
      sym_variant_definition,
      sym_record_definition,
      sym_tuple_definition,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [167] = 7,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(35), 1,
      sym_integer,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    STATE(105), 1,
      sym_primary_expression,
    STATE(118), 1,
      sym_literal,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(102), 2,
      sym_boolean,
      sym_string,
  [191] = 5,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(137), 1,
      sym_type_list,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(37), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [210] = 5,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(135), 1,
      sym_type_list,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(37), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [229] = 5,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(134), 1,
      sym_type_list,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(37), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [248] = 5,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(131), 1,
      sym_type_list,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(37), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [267] = 5,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(130), 1,
      sym_type_list,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(37), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [286] = 5,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(125), 1,
      sym_type_list,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(37), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [305] = 5,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(101), 1,
      sym_type_list,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(37), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [324] = 5,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(114), 1,
      sym_type_list,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(37), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [343] = 4,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    STATE(40), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(94), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [359] = 4,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    STATE(40), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(86), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [375] = 4,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(51), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [391] = 4,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    STATE(38), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(71), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [407] = 4,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    STATE(40), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(99), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [423] = 4,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    STATE(40), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(96), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [439] = 4,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(45), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [455] = 4,
    ACTIONS(45), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    STATE(38), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(65), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [471] = 4,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    STATE(30), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(60), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [487] = 4,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    STATE(40), 2,
      sym__simple_type,
      sym_generic_type,
    STATE(87), 3,
      sym__type,
      sym_function_type,
      sym_tuple_type,
  [503] = 4,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(83), 1,
      sym_param,
    STATE(33), 2,
      sym_record_type_field,
      aux_sym_record_definition_repeat1,
    STATE(58), 2,
      sym_variant_type_value,
      aux_sym_variant_definition_repeat1,
  [518] = 4,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(83), 1,
      sym_param,
    STATE(32), 2,
      sym_record_type_field,
      aux_sym_record_definition_repeat1,
    STATE(54), 2,
      sym_variant_type_value,
      aux_sym_variant_definition_repeat1,
  [533] = 3,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    STATE(39), 1,
      sym_type_arguments,
    ACTIONS(51), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [546] = 4,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym__dedent,
    STATE(83), 1,
      sym_param,
    STATE(31), 2,
      sym_record_type_field,
      aux_sym_record_definition_repeat1,
  [560] = 4,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(62), 1,
      sym__dedent,
    STATE(83), 1,
      sym_param,
    STATE(31), 2,
      sym_record_type_field,
      aux_sym_record_definition_repeat1,
  [574] = 4,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(64), 1,
      sym__dedent,
    STATE(83), 1,
      sym_param,
    STATE(31), 2,
      sym_record_type_field,
      aux_sym_record_definition_repeat1,
  [588] = 2,
    ACTIONS(66), 1,
      anon_sym_COLON,
    ACTIONS(68), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACK,
      anon_sym_COMMA,
  [598] = 1,
    ACTIONS(70), 5,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [606] = 4,
    ACTIONS(74), 1,
      anon_sym_COLON,
    ACTIONS(76), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_variant_type_value_args,
    ACTIONS(72), 2,
      sym__dedent,
      sym_identifier,
  [620] = 4,
    ACTIONS(80), 1,
      anon_sym_DASH_GT,
    ACTIONS(82), 1,
      anon_sym_COMMA,
    STATE(42), 1,
      aux_sym_type_list_repeat1,
    ACTIONS(78), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [634] = 3,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    STATE(46), 1,
      sym_type_arguments,
    ACTIONS(51), 3,
      sym__dedent,
      anon_sym_DASH_GT,
      sym_identifier,
  [646] = 1,
    ACTIONS(86), 5,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [654] = 3,
    ACTIONS(88), 1,
      anon_sym_LBRACK,
    STATE(72), 1,
      sym_type_arguments,
    ACTIONS(51), 2,
      sym__indent,
      anon_sym_DASH_GT,
  [665] = 3,
    ACTIONS(90), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      aux_sym_string_repeat1,
    ACTIONS(92), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [676] = 3,
    ACTIONS(82), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_type_list_repeat1,
    ACTIONS(95), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [687] = 3,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      aux_sym_string_repeat1,
    ACTIONS(99), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [698] = 3,
    ACTIONS(101), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      aux_sym_string_repeat1,
    ACTIONS(103), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [709] = 2,
    ACTIONS(80), 1,
      anon_sym_DASH_GT,
    ACTIONS(105), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [718] = 1,
    ACTIONS(86), 4,
      sym__dedent,
      anon_sym_DASH_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [725] = 4,
    ACTIONS(107), 1,
      sym_identifier,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_param,
    STATE(116), 1,
      sym_parameter_list,
  [738] = 4,
    ACTIONS(107), 1,
      sym_identifier,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_param,
    STATE(103), 1,
      sym_parameter_list,
  [751] = 1,
    ACTIONS(70), 4,
      sym__dedent,
      anon_sym_DASH_GT,
      anon_sym_LBRACK,
      sym_identifier,
  [758] = 3,
    ACTIONS(113), 1,
      anon_sym_DQUOTE,
    STATE(52), 1,
      aux_sym_string_repeat1,
    ACTIONS(115), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [769] = 2,
    ACTIONS(80), 1,
      anon_sym_DASH_GT,
    ACTIONS(117), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [778] = 3,
    ACTIONS(119), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      aux_sym_string_repeat1,
    ACTIONS(103), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [789] = 3,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_type_list_repeat1,
    ACTIONS(121), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [800] = 3,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(128), 1,
      sym__dedent,
    STATE(56), 2,
      sym_variant_type_value,
      aux_sym_variant_definition_repeat1,
  [811] = 3,
    ACTIONS(76), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_variant_type_value_args,
    ACTIONS(72), 2,
      sym__dedent,
      sym_identifier,
  [822] = 3,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(133), 1,
      sym__dedent,
    STATE(56), 2,
      sym_variant_type_value,
      aux_sym_variant_definition_repeat1,
  [833] = 4,
    ACTIONS(135), 1,
      anon_sym_COLON,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    STATE(89), 1,
      sym_type_param_clause,
  [846] = 3,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(141), 1,
      sym__dedent,
    STATE(56), 2,
      sym_variant_type_value,
      aux_sym_variant_definition_repeat1,
  [857] = 1,
    ACTIONS(143), 4,
      anon_sym_RPAREN,
      anon_sym_DASH_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [864] = 2,
    ACTIONS(80), 1,
      anon_sym_DASH_GT,
    ACTIONS(145), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [872] = 1,
    ACTIONS(147), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_fun,
  [878] = 3,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    STATE(128), 1,
      sym_type_param_clause,
  [888] = 1,
    ACTIONS(151), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_fun,
  [894] = 1,
    ACTIONS(153), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_fun,
  [900] = 2,
    ACTIONS(155), 1,
      anon_sym_DASH_GT,
    ACTIONS(105), 2,
      sym__dedent,
      sym_identifier,
  [908] = 1,
    ACTIONS(143), 3,
      sym__dedent,
      anon_sym_DASH_GT,
      sym_identifier,
  [914] = 3,
    ACTIONS(157), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RBRACK,
    STATE(82), 1,
      aux_sym_type_param_clause_repeat1,
  [924] = 3,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_type_param_clause_repeat1,
  [934] = 1,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_fun,
  [940] = 1,
    ACTIONS(70), 3,
      sym__indent,
      anon_sym_DASH_GT,
      anon_sym_LBRACK,
  [946] = 2,
    ACTIONS(155), 1,
      anon_sym_DASH_GT,
    ACTIONS(145), 2,
      sym__dedent,
      sym_identifier,
  [954] = 1,
    ACTIONS(86), 3,
      sym__indent,
      anon_sym_DASH_GT,
      anon_sym_LBRACK,
  [960] = 3,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_parameter_list_repeat1,
  [970] = 1,
    ACTIONS(173), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_fun,
  [976] = 1,
    ACTIONS(175), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_fun,
  [982] = 1,
    ACTIONS(177), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_fun,
  [988] = 3,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_parameter_list_repeat1,
  [998] = 3,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_parameter_list_repeat1,
  [1008] = 1,
    ACTIONS(185), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_fun,
  [1014] = 1,
    ACTIONS(187), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_fun,
  [1020] = 1,
    ACTIONS(189), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_fun,
  [1026] = 3,
    ACTIONS(157), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_type_param_clause_repeat1,
  [1036] = 1,
    ACTIONS(193), 2,
      sym__dedent,
      sym_identifier,
  [1041] = 1,
    ACTIONS(195), 2,
      sym__dedent,
      sym_identifier,
  [1046] = 2,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(67), 1,
      sym_type_param,
  [1053] = 2,
    ACTIONS(199), 1,
      anon_sym_DASH_GT,
    ACTIONS(201), 1,
      sym__indent,
  [1060] = 2,
    ACTIONS(199), 1,
      anon_sym_DASH_GT,
    ACTIONS(203), 1,
      sym__indent,
  [1067] = 1,
    ACTIONS(205), 2,
      sym__dedent,
      sym_identifier,
  [1072] = 2,
    ACTIONS(207), 1,
      anon_sym_COLON,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
  [1079] = 1,
    ACTIONS(164), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1084] = 1,
    ACTIONS(211), 2,
      anon_sym_COLON,
      anon_sym_LPAREN,
  [1089] = 1,
    ACTIONS(213), 2,
      anon_sym_COLON,
      anon_sym_LPAREN,
  [1094] = 1,
    ACTIONS(215), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1099] = 2,
    ACTIONS(199), 1,
      anon_sym_DASH_GT,
    ACTIONS(217), 1,
      sym__indent,
  [1106] = 2,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(90), 1,
      sym_type_param,
  [1113] = 2,
    ACTIONS(199), 1,
      anon_sym_DASH_GT,
    ACTIONS(219), 1,
      sym__indent,
  [1120] = 1,
    ACTIONS(168), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1125] = 2,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(97), 1,
      sym_param,
  [1132] = 2,
    ACTIONS(105), 1,
      sym__indent,
    ACTIONS(199), 1,
      anon_sym_DASH_GT,
  [1139] = 1,
    ACTIONS(143), 2,
      sym__indent,
      anon_sym_DASH_GT,
  [1144] = 1,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
  [1148] = 1,
    ACTIONS(223), 1,
      sym__dedent,
  [1152] = 1,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
  [1156] = 1,
    ACTIONS(227), 1,
      anon_sym_PLUS,
  [1160] = 1,
    ACTIONS(229), 1,
      sym__dedent,
  [1164] = 1,
    ACTIONS(231), 1,
      anon_sym_RPAREN,
  [1168] = 1,
    ACTIONS(233), 1,
      anon_sym_DASH_GT,
  [1172] = 1,
    ACTIONS(235), 1,
      sym__dedent,
  [1176] = 1,
    ACTIONS(237), 1,
      anon_sym_DASH_GT,
  [1180] = 1,
    ACTIONS(66), 1,
      anon_sym_COLON,
  [1184] = 1,
    ACTIONS(239), 1,
      anon_sym_DASH_GT,
  [1188] = 1,
    ACTIONS(241), 1,
      anon_sym_DASH_GT,
  [1192] = 1,
    ACTIONS(243), 1,
      sym__indent,
  [1196] = 1,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
  [1200] = 1,
    ACTIONS(247), 1,
      sym__dedent,
  [1204] = 1,
    ACTIONS(249), 1,
      anon_sym_RPAREN,
  [1208] = 1,
    ACTIONS(251), 1,
      sym_identifier,
  [1212] = 1,
    ACTIONS(253), 1,
      sym__dedent,
  [1216] = 1,
    ACTIONS(255), 1,
      sym__dedent,
  [1220] = 1,
    ACTIONS(257), 1,
      sym__dedent,
  [1224] = 1,
    ACTIONS(259), 1,
      sym__dedent,
  [1228] = 1,
    ACTIONS(227), 1,
      sym__dedent,
  [1232] = 1,
    ACTIONS(259), 1,
      anon_sym_PLUS,
  [1236] = 1,
    ACTIONS(261), 1,
      anon_sym_PLUS,
  [1240] = 1,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
  [1244] = 1,
    ACTIONS(265), 1,
      sym__dedent,
  [1248] = 1,
    ACTIONS(223), 1,
      anon_sym_PLUS,
  [1252] = 1,
    ACTIONS(267), 1,
      anon_sym_LPAREN,
  [1256] = 1,
    ACTIONS(74), 1,
      anon_sym_COLON,
  [1260] = 1,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
  [1264] = 1,
    ACTIONS(271), 1,
      anon_sym_RBRACK,
  [1268] = 1,
    ACTIONS(255), 1,
      anon_sym_PLUS,
  [1272] = 1,
    ACTIONS(253), 1,
      anon_sym_PLUS,
  [1276] = 1,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
  [1280] = 1,
    ACTIONS(275), 1,
      anon_sym_RBRACK,
  [1284] = 1,
    ACTIONS(277), 1,
      sym__indent,
  [1288] = 1,
    ACTIONS(279), 1,
      anon_sym_RBRACK,
  [1292] = 1,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
  [1296] = 1,
    ACTIONS(283), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 77,
  [SMALL_STATE(6)] = 104,
  [SMALL_STATE(7)] = 131,
  [SMALL_STATE(8)] = 149,
  [SMALL_STATE(9)] = 167,
  [SMALL_STATE(10)] = 191,
  [SMALL_STATE(11)] = 210,
  [SMALL_STATE(12)] = 229,
  [SMALL_STATE(13)] = 248,
  [SMALL_STATE(14)] = 267,
  [SMALL_STATE(15)] = 286,
  [SMALL_STATE(16)] = 305,
  [SMALL_STATE(17)] = 324,
  [SMALL_STATE(18)] = 343,
  [SMALL_STATE(19)] = 359,
  [SMALL_STATE(20)] = 375,
  [SMALL_STATE(21)] = 391,
  [SMALL_STATE(22)] = 407,
  [SMALL_STATE(23)] = 423,
  [SMALL_STATE(24)] = 439,
  [SMALL_STATE(25)] = 455,
  [SMALL_STATE(26)] = 471,
  [SMALL_STATE(27)] = 487,
  [SMALL_STATE(28)] = 503,
  [SMALL_STATE(29)] = 518,
  [SMALL_STATE(30)] = 533,
  [SMALL_STATE(31)] = 546,
  [SMALL_STATE(32)] = 560,
  [SMALL_STATE(33)] = 574,
  [SMALL_STATE(34)] = 588,
  [SMALL_STATE(35)] = 598,
  [SMALL_STATE(36)] = 606,
  [SMALL_STATE(37)] = 620,
  [SMALL_STATE(38)] = 634,
  [SMALL_STATE(39)] = 646,
  [SMALL_STATE(40)] = 654,
  [SMALL_STATE(41)] = 665,
  [SMALL_STATE(42)] = 676,
  [SMALL_STATE(43)] = 687,
  [SMALL_STATE(44)] = 698,
  [SMALL_STATE(45)] = 709,
  [SMALL_STATE(46)] = 718,
  [SMALL_STATE(47)] = 725,
  [SMALL_STATE(48)] = 738,
  [SMALL_STATE(49)] = 751,
  [SMALL_STATE(50)] = 758,
  [SMALL_STATE(51)] = 769,
  [SMALL_STATE(52)] = 778,
  [SMALL_STATE(53)] = 789,
  [SMALL_STATE(54)] = 800,
  [SMALL_STATE(55)] = 811,
  [SMALL_STATE(56)] = 822,
  [SMALL_STATE(57)] = 833,
  [SMALL_STATE(58)] = 846,
  [SMALL_STATE(59)] = 857,
  [SMALL_STATE(60)] = 864,
  [SMALL_STATE(61)] = 872,
  [SMALL_STATE(62)] = 878,
  [SMALL_STATE(63)] = 888,
  [SMALL_STATE(64)] = 894,
  [SMALL_STATE(65)] = 900,
  [SMALL_STATE(66)] = 908,
  [SMALL_STATE(67)] = 914,
  [SMALL_STATE(68)] = 924,
  [SMALL_STATE(69)] = 934,
  [SMALL_STATE(70)] = 940,
  [SMALL_STATE(71)] = 946,
  [SMALL_STATE(72)] = 954,
  [SMALL_STATE(73)] = 960,
  [SMALL_STATE(74)] = 970,
  [SMALL_STATE(75)] = 976,
  [SMALL_STATE(76)] = 982,
  [SMALL_STATE(77)] = 988,
  [SMALL_STATE(78)] = 998,
  [SMALL_STATE(79)] = 1008,
  [SMALL_STATE(80)] = 1014,
  [SMALL_STATE(81)] = 1020,
  [SMALL_STATE(82)] = 1026,
  [SMALL_STATE(83)] = 1036,
  [SMALL_STATE(84)] = 1041,
  [SMALL_STATE(85)] = 1046,
  [SMALL_STATE(86)] = 1053,
  [SMALL_STATE(87)] = 1060,
  [SMALL_STATE(88)] = 1067,
  [SMALL_STATE(89)] = 1072,
  [SMALL_STATE(90)] = 1079,
  [SMALL_STATE(91)] = 1084,
  [SMALL_STATE(92)] = 1089,
  [SMALL_STATE(93)] = 1094,
  [SMALL_STATE(94)] = 1099,
  [SMALL_STATE(95)] = 1106,
  [SMALL_STATE(96)] = 1113,
  [SMALL_STATE(97)] = 1120,
  [SMALL_STATE(98)] = 1125,
  [SMALL_STATE(99)] = 1132,
  [SMALL_STATE(100)] = 1139,
  [SMALL_STATE(101)] = 1144,
  [SMALL_STATE(102)] = 1148,
  [SMALL_STATE(103)] = 1152,
  [SMALL_STATE(104)] = 1156,
  [SMALL_STATE(105)] = 1160,
  [SMALL_STATE(106)] = 1164,
  [SMALL_STATE(107)] = 1168,
  [SMALL_STATE(108)] = 1172,
  [SMALL_STATE(109)] = 1176,
  [SMALL_STATE(110)] = 1180,
  [SMALL_STATE(111)] = 1184,
  [SMALL_STATE(112)] = 1188,
  [SMALL_STATE(113)] = 1192,
  [SMALL_STATE(114)] = 1196,
  [SMALL_STATE(115)] = 1200,
  [SMALL_STATE(116)] = 1204,
  [SMALL_STATE(117)] = 1208,
  [SMALL_STATE(118)] = 1212,
  [SMALL_STATE(119)] = 1216,
  [SMALL_STATE(120)] = 1220,
  [SMALL_STATE(121)] = 1224,
  [SMALL_STATE(122)] = 1228,
  [SMALL_STATE(123)] = 1232,
  [SMALL_STATE(124)] = 1236,
  [SMALL_STATE(125)] = 1240,
  [SMALL_STATE(126)] = 1244,
  [SMALL_STATE(127)] = 1248,
  [SMALL_STATE(128)] = 1252,
  [SMALL_STATE(129)] = 1256,
  [SMALL_STATE(130)] = 1260,
  [SMALL_STATE(131)] = 1264,
  [SMALL_STATE(132)] = 1268,
  [SMALL_STATE(133)] = 1272,
  [SMALL_STATE(134)] = 1276,
  [SMALL_STATE(135)] = 1280,
  [SMALL_STATE(136)] = 1284,
  [SMALL_STATE(137)] = 1288,
  [SMALL_STATE(138)] = 1292,
  [SMALL_STATE(139)] = 1296,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(117),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(139),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_definition_repeat1, 2), SHIFT_REPEAT(129),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_definition_repeat1, 2),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_type, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arguments, 3),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_type_value, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 1, .production_id = 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_type, 2, .production_id = 5),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(41),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 2, .production_id = 4),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 3, .production_id = 8),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2, .production_id = 9),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2, .production_id = 10),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2, .production_id = 10), SHIFT_REPEAT(20),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variant_definition_repeat1, 2), SHIFT_REPEAT(55),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variant_definition_repeat1, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, .production_id = 12),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_definition, 5, .production_id = 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_definition, 6, .production_id = 6),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_definition, 6, .production_id = 7),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_param_clause_repeat1, 2), SHIFT_REPEAT(95),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_param_clause_repeat1, 2),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_definition, 6, .production_id = 11),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(98),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 11, .production_id = 18),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 10, .production_id = 17),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 10, .production_id = 16),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 9, .production_id = 15),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_definition, 7, .production_id = 13),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_definition, 7, .production_id = 14),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type_field, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_type_value, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variant_type_value_args, 3),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_param_clause, 4),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_param_clause, 3),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_param, 1, .production_id = 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_infix_expression, 3),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [281] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_fuse_external_scanner_create(void);
void tree_sitter_fuse_external_scanner_destroy(void *);
bool tree_sitter_fuse_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_fuse_external_scanner_serialize(void *, char *);
void tree_sitter_fuse_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_fuse(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_fuse_external_scanner_create,
      tree_sitter_fuse_external_scanner_destroy,
      tree_sitter_fuse_external_scanner_scan,
      tree_sitter_fuse_external_scanner_serialize,
      tree_sitter_fuse_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
